// Generated by delombok at Sat Apr 06 10:25:55 EDT 2019
package com.bsg5.chapter8;

import org.springframework.lang.NonNull;

public class Artist {
    Integer id;
    @NonNull
    String name;

    @java.lang.SuppressWarnings("all")
    public Integer getId() {
        return this.id;
    }

    @NonNull
    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Integer id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(@NonNull final String name) {
        if (name == null) {
            throw new java.lang.NullPointerException("name is marked @NonNull but is null");
        }
        this.name = name;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Artist)) return false;
        final Artist other = (Artist) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Artist;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Artist(id=" + this.getId() + ", name=" + this.getName() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Artist(final Integer id, @NonNull final String name) {
        if (name == null) {
            throw new java.lang.NullPointerException("name is marked @NonNull but is null");
        }
        this.id = id;
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public Artist(@NonNull final String name) {
        if (name == null) {
            throw new java.lang.NullPointerException("name is marked @NonNull but is null");
        }
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public Artist() {
    }
}
