INSERT INTO ARTISTS (ID, NAME)
VALUES (1, 'Threadbare Loaf');
INSERT INTO ARTISTS (ID, NAME)
VALUES (2, 'Therapy Zeppelin');
INSERT INTO ARTISTS (ID, NAME)
VALUES (3, 'Clancy In Silt');

INSERT INTO SONGS (ID, ARTIST_ID, NAME, VOTES)
VALUES (1, 1, 'Someone Stole the Flour', 4);
INSERT INTO SONGS (ID, ARTIST_ID, NAME, VOTES)
VALUES (2, 1, 'What Happened to Our First CD?', 17);
INSERT INTO SONGS (ID, ARTIST_ID, NAME, VOTES)
VALUES (3, 2, 'Medium', 4);
INSERT INTO SONGS (ID, ARTIST_ID, NAME, VOTES)
VALUES (4, 3, 'Igneous', 5);